import {
  ARTIFICIAL_SECURITY_DIRECTORS_OVERADVANCE_AGENDA_ID,
  CHICAGO_BRANCH_COUNTER_ASSET_ID,
  FALSIFIED_TRANSACTIONS_EXPERT_COUNTER_OPERATION_ID,
  GENETICS_VISIONARY_ACQUISITION_OVERADVANCE_AGENDA_ID,
  MANAGEMENT_SHAKE_UP_ADVANCEMENT_OPERATION_ID,
  ROVING_SUBMARINE_AGENDA_DIFFICULTY_UPGRADE_ID,
  TEAM_RESTRUCTURING_COUNTER_OPERATION_ID,
  VAPOR_OPS_COUNTER_ASSET_ID,
  WASHINGTON_DC_AGENDA_DIFFICULTY_UPGRADE_ID,
} from "./agenda-operation-effects";

export const OVERADVANCE_AGENDA_CARD_IDS = new Set([
  ARTIFICIAL_SECURITY_DIRECTORS_OVERADVANCE_AGENDA_ID,
  GENETICS_VISIONARY_ACQUISITION_OVERADVANCE_AGENDA_ID,
]);

export const SCORED_REVEAL_AGENDA_CARD_IDS = new Set([
  ARTIFICIAL_SECURITY_DIRECTORS_OVERADVANCE_AGENDA_ID,
  GENETICS_VISIONARY_ACQUISITION_OVERADVANCE_AGENDA_ID,
]);

export const SERVER_DIFFICULTY_UPGRADE_CARD_IDS = new Set([
  ROVING_SUBMARINE_AGENDA_DIFFICULTY_UPGRADE_ID,
  WASHINGTON_DC_AGENDA_DIFFICULTY_UPGRADE_ID,
]);

export const COUNTER_ASSET_CARD_IDS = new Set([
  CHICAGO_BRANCH_COUNTER_ASSET_ID,
  VAPOR_OPS_COUNTER_ASSET_ID,
]);

export const COUNTER_OPERATION_CARD_IDS = new Set([
  FALSIFIED_TRANSACTIONS_EXPERT_COUNTER_OPERATION_ID,
  MANAGEMENT_SHAKE_UP_ADVANCEMENT_OPERATION_ID,
  TEAM_RESTRUCTURING_COUNTER_OPERATION_ID,
]);

export const ACTION_ASSET_CARD_IDS = new Set([
  "onr_v1_331_nevinyrral",
  "onr_v1_334_pacifica-regional-ai",
  "onr_v1_335_remote-facility",
]);
