import {
  CORP_RUN_TAX_UPGRADE_CARD_IDS,
  CORP_TRACE_ASSET_CARD_IDS,
} from "./card-implementation-derived-sets";

export const TRACE_ASSET_CARD_IDS = CORP_TRACE_ASSET_CARD_IDS;
export const RUN_TAX_UPGRADE_CARD_IDS = CORP_RUN_TAX_UPGRADE_CARD_IDS;
