/**
 * Public runtime facade for engine consumers and the package entrypoint.
 *
 * This file intentionally exposes only the supported runtime API. Private
 * bootstrap, host, and resolver modules stay below engine-runtime-internal.
 */

export {
  getLegalActions,
  legalActionsFor,
  eventVisibilityForAction,
  isHiddenInfoBarrierEvent,
  checkWinConditions,
  quoteCorpRezCost,
  createGame,
  createGameAfterSetup,
  applyAction,
  applyGameAction,
  getPlayerView,
  playerViewFor,
  replayEvents,
  replayGameEvents,
  redactPublicEventForSide,
  hashGameState,
  hashState,
  validateGameState,
  validateGameStateForDebug,
  validateDeckDefinition,
  applyEffectCommands,
  CARD_DEFINITIONS,
  CARD_DEFINITIONS_BY_ID,
  DEMO_DECKS,
  CURRENT_RULES_BASELINE,
} from "./engine-runtime-internal/public-api";

export type {
  ActionType,
  ChoiceRequest,
  CardDefinition,
  CardDefinitionId,
  CardInstance,
  CardInstanceId,
  CardType,
  CounterType,
  CorpServer,
  CreateGameConfig,
  DeckDefinition,
  DeckPublicMetadata,
  DemoDeckId,
  DamageType,
  ApplyActionOptions,
  EngineError,
  EngineResult,
  EventVisibilityClass,
  EventModificationCandidate,
  EventModificationWindow,
  EffectCommand,
  GameEvent,
  GameEndReason,
  GameState,
  ImminentEvent,
  LegalAction,
  PlayerAction,
  PlayerController,
  PlayerView,
  PublicGameEvent,
  ReplacementCandidate,
  ReplacementWindow,
  ReplayResult,
  RulesBaseline,
  ServerId,
  SetupState,
  Side,
  StateHash,
  SpecialZoneKind,
  SpecialZoneState,
  SpecialZoneVisibility,
  ValidationResult,
  VisibleCard,
  Winner,
} from "./engine-runtime-internal/public-api";
