import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import * as ai from "./index";

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../..",
);

describe("AI public export contract", () => {
  it("keeps established runtime, benchmark and legacy facades exported", () => {
    const publicKeys = Object.keys(ai);
    const expectedExports = [
      "chooseAiAction",
      "chooseCorpAction",
      "chooseRunnerAction",
      "chooseCorpBaselineAction",
      "chooseRunnerBaselineAction",
      "buildAiDecisionInput",
      "buildAiDecisionInputDto",
      "assertAiInputIsSideSafe",
      "runAiSelfplayTraceMining",
      "detectAiSelfplaySuspiciousDecisions",
      "formatAiSelfplayTraceMiningReport",
      "runMatchProgressionBenchmark",
      "runMatchProgressionBenchmarkSuite",
      "formatMatchProgressionBenchmarkReport",
      "formatMatchProgressionBenchmarkSuiteReport",
      "runDoctrineQualityBenchmark",
      "formatDoctrineQualityBenchmarkReport",
      "evaluateDoctrineQualityGate",
      "summarizeActionSemanticCandidateCoverage",
      "formatActionSemanticCandidateCoverageReport",
      "buildDeckStrategyProfile",
      "reconstructBeliefState",
    ];

    for (const exportName of expectedExports) {
      expect(publicKeys).toContain(exportName);
      expect(typeof ai[exportName as keyof typeof ai]).toBe("function");
    }
  });

  it("keeps new play-strength diagnostics and evaluation helpers internal by default", () => {
    const publicKeys = Object.keys(ai);
    const internalExports = [
      "buildSemanticRuntimeDebugPlanContext",
      "semanticRuntimeDebugRankedAlternatives",
      "buildSemanticShadowLeagueDeltaReport",
      "buildSelfplayDecisionSnapshotMiningReport",
      "buildSemanticShadowLeagueReport",
      "buildTargetChoiceShadowCandidateCoverageReport",
      "buildDoctrineGoalCoverageReport",
      "buildLocalDefaultPilotPolicy",
      "evaluateRemoteContestCandidate",
      "buildTargetChoiceShadowReport",
      "buildTargetChoiceSelectedChoicesReadinessReport",
      "buildDoctrineGoalActionFitReport",
      "buildSelfplayDecisionSnapshotPromotionQueue",
      "buildSelfplayPromotedRealEngineCorpusScenarios",
      "recommendedLocalDefaultScopes",
      "buildRuntimeScoreBreakdown",
      "aggregateDoctrineMetricSums",
      "projectKnownRemoteTrashCommitment",
      "projectAccessDecision",
      "projectAccessWindowChoice",
      "rankKnownRemoteAccessTargets",
      "buildRealEngineAccessCorpus",
      "detectRepeatedNoPayoffAccessLoop",
      "buildProteusRandomModelReadinessReport",
      "formatSemanticShadowLeagueDeltaDashboard",
      "formatSelfplayPromotionActivityCandidates",
    ];

    for (const exportName of internalExports) {
      expect(publicKeys).not.toContain(exportName);
    }
  });

  it("does not export evaluation test helpers or diagnostic-only modules through index", () => {
    const source = readFileSync(
      path.join(repoRoot, "packages/ai/src/index.ts"),
      "utf8",
    );
    const forbiddenPublicModules = [
      "./diagnostics/semantic-runtime-debug",
      "./diagnostics/coverage-selection-debug",
      "./diagnostics/semantic-runtime-action-alternatives",
      "./diagnostics/semantic-runtime-ranked-alternatives",
      "./diagnostics/semantic-runtime-decision-debug",
      "./evaluation/semantic-shadow-league-delta",
      "./evaluation/selfplay-decision-snapshot-mining",
      "./evaluation/semantic-shadow-league",
      "./evaluation/target-choice-shadow-coverage",
      "./evaluation/target-choice-shadow-readiness",
      "./evaluation/proteus-random-model-readiness",
      "./evaluation/doctrine-goal-action-fit",
      "./evaluation/doctrine-goal-coverage",
      "./decision/known-remote-access-commitment",
      "./decision/access-decision-projection",
      "./access/access-window-choice",
      "./access/access-target-ranking",
      "./access/access-outcome-memory",
      "./access/remote-access-fingerprint",
      "./evaluation/real-engine-access-corpus",
      "./evaluation/access-loop-detection",
      "./decision/pilot/local-default-pilot-policy",
      "./decision/pilot/remote-contest-candidate",
      "./decision/target-choice-shadow",
      "./runtime/semantic-runtime-score-components",
      "./runtime/semantic-runtime-score-breakdown",
      "./runtime/semantic-runtime-debug-context",
      "./runtime/semantic-runtime-decision-context",
      "./runtime/semantic-runtime-runner-evidence",
      "./runtime/semantic-runtime-runner-evidence-context",
      "./runtime/semantic-runtime-corp-evidence",
      "./runtime/semantic-runtime-corp-evidence-context",
      "./runtime/semantic-runtime-evidence",
      "./runtime/semantic-runtime-evidence-context",
      "./runtime/semantic-runtime-corp-risk",
      "./runtime/semantic-runtime-corp-risk-context",
      "./runtime/semantic-runtime-corp-rez-floor",
      "./runtime/semantic-runtime-corp-rez-floor-context",
      "./runtime/semantic-runtime-corp-remote-score",
      "./runtime/semantic-runtime-corp-remote-score-context",
      "./runtime/semantic-runtime-corp-passive-scoreline",
      "./runtime/semantic-runtime-corp-passive-scoreline-context",
      "./runtime/semantic-runtime-corp-advancement-counter",
      "./runtime/semantic-runtime-corp-advancement-counter-context",
      "./runtime/semantic-runtime-corp-board",
      "./runtime/semantic-runtime-corp-board-context",
      "./runtime/semantic-runtime-corp-score-safety",
      "./runtime/semantic-runtime-corp-score-safety-context",
      "./runtime/semantic-runtime-scope",
      "./runtime/semantic-runtime-explanation",
      "./runtime/record-value",
      "./runtime/action-cost",
      "./runtime/collection",
      "./runtime/counter",
      "./runtime/evidence-value",
      "./runtime/number-rounding",
      "./runtime/public-event-history",
      "./runtime/choice-option",
      "./runtime/role-match",
      "./runtime/semantic-runtime-choice-builder",
      "./runtime/semantic-runtime-choice-builder-context",
      "./runtime/semantic-runtime-action-exclusion",
      "./runtime/semantic-runtime-action-exclusion-context",
      "./runtime/runner-run-only-action-adjustment",
      "./runtime/runner-self-damage-choice",
      "./runtime/runner-self-damage-context",
      "./runtime/runner-baseline-plan-guard-context",
      "./runtime/runner-program-sacrifice-exclusion",
      "./runtime/runner-blink-run-exclusion",
      "./runtime/runner-blink-risk-context",
      "./runtime/runner-blink-break-exclusion",
      "./runtime/runner-encounter-action-exclusion",
      "./runtime/known-central-payoff-exclusion",
      "./runtime/runner-simple-exclusions-context",
      "./runtime/semantic-runtime-plan-memory-exclusion",
      "./runtime/runner-archives-exclusion",
      "./runtime/runner-source-card-answer-role",
      "./runtime/runner-source-card-answer-role-context",
      "./runtime/runner-hand-buffer-need",
      "./runtime/runner-hand-funding-context",
      "./runtime/runner-hand-funding-target",
      "./runtime/runner-tag-cleanup-score",
      "./runtime/runner-credit-need-score",
      "./runtime/runner-install-score",
      "./runtime/runner-start-run-score",
      "./runtime/runner-basic-action-penalty-score",
      "./runtime/runner-followup-score",
      "./runtime/runner-loan-liability-score",
      "./runtime/runner-loan-liability-assessment",
      "./runtime/runner-loan-credit-projection",
      "./runtime/runner-loan-run-funding-context",
      "./runtime/runner-loan-runtime-context",
      "./runtime/runner-loan-projected-spend",
      "./runtime/runner-loan-spend-candidate",
      "./runtime/runner-loan-source",
      "./runtime/runner-loan-liability-policy",
      "./runtime/runner-loan-state-context",
      "./runtime/runner-loan-funding-need",
      "./runtime/runner-loan-context",
      "./runtime/runner-recovery-commitment-score",
      "./runtime/runner-recovery-context",
      "./runtime/runner-score-components",
      "./runtime/runner-multi-run-event-assessment",
      "./runtime/runner-multi-run-event-score",
      "./runtime/runner-multi-run-event-exclusion",
      "./runtime/runner-multi-run-context",
      "./runtime/runner-economy-commitment-score",
      "./runtime/runner-bank-investment-context",
      "./runtime/runner-no-run-economy-context",
      "./runtime/runner-bad-publicity-relevance-score",
      "./runtime/runner-bad-publicity-relevance-assessment",
      "./runtime/runner-bad-publicity-relevance-context",
      "./runtime/runner-viral15-jack-out-score",
      "./runtime/runner-viral15-jack-out-context",
      "./runtime/runner-blink-recovery-score",
      "./runtime/runner-recovery-repeat-score",
      "./runtime/runner-recovery-funding-need",
      "./runtime/runner-recovery-history",
      "./runtime/runner-junkyard-bbs-recovery-score",
      "./runtime/runner-junkyard-bbs-recovery-target",
      "./runtime/runner-persistent-install-fit-score",
      "./runtime/runner-persistent-install-context",
      "./runtime/runner-mu-pressure-score",
      "./runtime/runner-mu-pressure-assessment",
      "./runtime/runner-mu-pressure-action-evidence",
      "./runtime/runner-mu-pressure-memory-support",
      "./runtime/runner-mu-pressure-policy",
      "./runtime/runner-mu-pressure-context",
      "./runtime/runner-program-install-trash-context",
      "./runtime/runner-program-install-trash-policy",
      "./runtime/runner-run-target-guidance-score",
      "./runtime/runner-run-target-guidance-context",
      "./runtime/runner-access-trash-score",
      "./runtime/runner-central-memory-score",
      "./runtime/runner-central-memory-context",
      "./runtime/runner-archives-score",
      "./runtime/runner-known-ice-path-score",
      "./runtime/runner-remote-score",
      "./runtime/runner-repeated-run-target-score",
      "./runtime/deck-capabilities-context",
      "./runtime/runner-run-components-context",
      "./runtime/runner-run-history",
      "./runtime/runner-recent-history-context",
      "./runtime/visible-card-heuristics",
      "./runtime/runner-visible-breaker-coverage",
      "./runtime/runner-visible-card-context",
      "./runtime/semantic-runtime-visible-card-context",
      "./runtime/semantic-runtime-doctrine-score",
      "./runtime/semantic-runtime-corp-doctrine-context",
      "./runtime/semantic-runtime-runner-doctrine-context",
      "./runtime/runner-strategic-intent-context",
      "./runtime/semantic-runtime-corp-score",
      "./runtime/semantic-runtime-corp-score-context",
      "./runtime/runner-goal-fit-score",
      "./runtime/legacy-decision-provider",
      "./runtime/reactive-action",
      "./simulation/simulation-metric-aggregation",
      "./reports/shadow-league-report-formatters",
      "./reports/selfplay-promotion-activity-formatters",
    ];

    for (const modulePath of forbiddenPublicModules) {
      expect(source).not.toMatch(
        new RegExp(`export\\s+(?:type\\s+)?(?:\\{|\\*)[\\s\\S]*?from\\s+["']${escapeRegExp(modulePath)}["']`),
      );
    }
    expect(source).not.toMatch(/export\s+(?:type\s+)?(?:\{|\*)[\s\S]*?\.test["']/);
  });
});

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
