import type { DeckDefinition } from "./index";
import type { DemoDeckId } from "./demo-fixtures";

export const DEMO_DECKS: Record<DemoDeckId, DeckDefinition> = {
  demo_runner_001: {
    id: "demo_runner_001",
    name: "Runner Demo Deck 01 - Run & Steal",
    side: "runner",
    identity: "runner_identity_001",
    cards: [
      { id: "simple_economy_event", quantity: 3 },
      { id: "simple_run_event", quantity: 3 },
      { id: "simple_fracter", quantity: 2 },
      { id: "simple_decoder", quantity: 2 },
      { id: "simple_killer", quantity: 2 },
    ],
  },
  demo_corp_001: {
    id: "demo_corp_001",
    name: "Corp Demo Deck 01 - Build & Score",
    side: "corp",
    identity: "corp_identity_001",
    cards: [
      { id: "simple_agenda", quantity: 3 },
      { id: "simple_economy_operation", quantity: 3 },
      { id: "simple_economy_asset", quantity: 3 },
      { id: "simple_barrier_ice", quantity: 3 },
      { id: "simple_code_gate_ice", quantity: 3 },
      { id: "simple_sentry_ice", quantity: 3 },
    ],
  },
  demo_runner_004: {
    id: "demo_runner_004",
    name: "Runner Demo Deck 04 - Setup & Pressure",
    side: "runner",
    identity: "runner_identity_001",
    cards: [
      { id: "simple_economy_event", quantity: 3 },
      { id: "simple_run_event", quantity: 3 },
      { id: "simple_draw_event", quantity: 3 },
      { id: "simple_setup_hardware", quantity: 2 },
      { id: "simple_fracter", quantity: 2 },
      { id: "efficient_fracter", quantity: 2 },
      { id: "simple_decoder", quantity: 2 },
      { id: "simple_killer", quantity: 2 },
    ],
  },
  demo_corp_004: {
    id: "demo_corp_004",
    name: "Corp Demo Deck 04 - Build, Tax & Tag",
    side: "corp",
    identity: "corp_identity_001",
    cards: [
      { id: "simple_agenda", quantity: 2 },
      { id: "simple_priority_agenda", quantity: 1 },
      { id: "simple_economy_operation", quantity: 3 },
      { id: "simple_draw_operation", quantity: 2 },
      { id: "simple_economy_asset", quantity: 2 },
      { id: "simple_upgrade", quantity: 2 },
      { id: "simple_barrier_ice", quantity: 2 },
      { id: "simple_taxing_barrier_ice", quantity: 2 },
      { id: "simple_code_gate_ice", quantity: 2 },
      { id: "simple_sentry_ice", quantity: 2 },
      { id: "simple_tag_ice", quantity: 2 },
      { id: "simple_tag_punishment_operation", quantity: 2 },
    ],
  },
  demo_runner_008: {
    id: "demo_runner_008",
    name: "Runner Demo Deck 08 - Starter Pressure",
    side: "runner",
    identity: "runner_identity_001",
    cards: [
      { id: "simple_economy_event", quantity: 3 },
      { id: "simple_run_event", quantity: 2 },
      { id: "simple_draw_event", quantity: 2 },
      { id: "simple_setup_hardware", quantity: 1 },
      { id: "simple_fracter", quantity: 2 },
      { id: "efficient_fracter", quantity: 2 },
      { id: "simple_decoder", quantity: 1 },
      { id: "simple_killer", quantity: 1 },
      { id: "v08_burst_credit_event", quantity: 3 },
      { id: "v08_deep_draw_event", quantity: 3 },
      { id: "v08_overclock_run_event", quantity: 2 },
      { id: "v08_memory_chip", quantity: 2 },
      { id: "v08_steady_fracter", quantity: 2 },
      { id: "v08_precise_decoder", quantity: 1 },
      { id: "v08_adaptive_killer", quantity: 1 },
    ],
  },
  demo_corp_008: {
    id: "demo_corp_008",
    name: "Corp Demo Deck 08 - Starter Score Grid",
    side: "corp",
    identity: "corp_identity_001",
    cards: [
      { id: "simple_agenda", quantity: 1 },
      { id: "simple_priority_agenda", quantity: 1 },
      { id: "v08_project_agenda", quantity: 1 },
      { id: "simple_economy_operation", quantity: 2 },
      { id: "simple_draw_operation", quantity: 1 },
      { id: "simple_economy_asset", quantity: 1 },
      { id: "simple_upgrade", quantity: 1 },
      { id: "simple_barrier_ice", quantity: 1 },
      { id: "simple_code_gate_ice", quantity: 1 },
      { id: "simple_sentry_ice", quantity: 1 },
      { id: "simple_tag_ice", quantity: 1 },
      { id: "simple_taxing_barrier_ice", quantity: 1 },
      { id: "v08_credit_surge_operation", quantity: 3 },
      { id: "v08_archive_planning_operation", quantity: 2 },
      { id: "v08_cashout_asset", quantity: 2 },
      { id: "v08_wall_ice", quantity: 2 },
      { id: "v08_gate_ice", quantity: 2 },
      { id: "v08_watchdog_ice", quantity: 2 },
    ],
  },
  demo_runner_096: {
    id: "demo_runner_096",
    name: "Runner Demo Deck 0.96 - Trace Bidding Harness",
    side: "runner",
    identity: "runner_identity_001",
    cards: [
      { id: "simple_economy_event", quantity: 3 },
      { id: "simple_run_event", quantity: 2 },
      { id: "simple_draw_event", quantity: 2 },
      { id: "simple_fracter", quantity: 1 },
      { id: "simple_decoder", quantity: 1 },
      { id: "simple_killer", quantity: 2 },
      { id: "v08_burst_credit_event", quantity: 2 },
      { id: "v095_safehouse_resource", quantity: 1 },
    ],
  },
  demo_corp_096: {
    id: "demo_corp_096",
    name: "Corp Demo Deck 0.96 - Trace Probe Harness",
    side: "corp",
    identity: "corp_identity_001",
    cards: [
      { id: "simple_agenda", quantity: 1 },
      { id: "simple_priority_agenda", quantity: 1 },
      { id: "v08_project_agenda", quantity: 1 },
      { id: "simple_economy_operation", quantity: 2 },
      { id: "simple_economy_asset", quantity: 1 },
      { id: "simple_barrier_ice", quantity: 1 },
      { id: "simple_tag_ice", quantity: 1 },
      { id: "v096_trace_probe_ice", quantity: 3 },
      { id: "v08_credit_surge_operation", quantity: 2 },
    ],
  },
  demo_runner_097: {
    id: "demo_runner_097",
    name: "Runner Demo Deck 0.97 - Breach Multiaccess Harness",
    side: "runner",
    identity: "runner_identity_001",
    cards: [
      { id: "simple_economy_event", quantity: 3 },
      { id: "simple_run_event", quantity: 2 },
      { id: "simple_draw_event", quantity: 2 },
      { id: "simple_fracter", quantity: 1 },
      { id: "simple_decoder", quantity: 1 },
      { id: "simple_killer", quantity: 2 },
      { id: "v08_burst_credit_event", quantity: 2 },
      { id: "v095_safehouse_resource", quantity: 1 },
      { id: "v097_deep_dive_event", quantity: 2 },
    ],
  },
  demo_corp_097: {
    id: "demo_corp_097",
    name: "Corp Demo Deck 0.97 - Breach Queue Harness",
    side: "corp",
    identity: "corp_identity_001",
    cards: [
      { id: "simple_agenda", quantity: 1 },
      { id: "simple_priority_agenda", quantity: 1 },
      { id: "v08_project_agenda", quantity: 1 },
      { id: "simple_economy_operation", quantity: 2 },
      { id: "simple_economy_asset", quantity: 1 },
      { id: "simple_upgrade", quantity: 1 },
      { id: "simple_barrier_ice", quantity: 1 },
      { id: "simple_tag_ice", quantity: 1 },
      { id: "v096_trace_probe_ice", quantity: 1 },
      { id: "v08_credit_surge_operation", quantity: 2 },
    ],
  },
  demo_runner_098: {
    id: "demo_runner_098",
    name: "Runner Demo Deck 0.98 - Identity Modifier Harness",
    side: "runner",
    identity: "v098_runner_identity",
    cards: [
      { id: "simple_economy_event", quantity: 3 },
      { id: "simple_run_event", quantity: 2 },
      { id: "simple_draw_event", quantity: 2 },
      { id: "simple_fracter", quantity: 2 },
      { id: "simple_decoder", quantity: 1 },
      { id: "simple_killer", quantity: 2 },
      { id: "v08_burst_credit_event", quantity: 2 },
      { id: "v095_safehouse_resource", quantity: 1 },
      { id: "v097_deep_dive_event", quantity: 2 },
      { id: "v098_stack_search_event", quantity: 1 },
      { id: "v098_stack_arrange_event", quantity: 1 },
      { id: "v098_reveal_top_event", quantity: 1 },
      { id: "v098_expose_event", quantity: 1 },
    ],
  },
  demo_corp_098: {
    id: "demo_corp_098",
    name: "Corp Demo Deck 0.98 - Identity Modifier Harness",
    side: "corp",
    identity: "v098_corp_identity",
    cards: [
      { id: "simple_agenda", quantity: 1 },
      { id: "simple_priority_agenda", quantity: 1 },
      { id: "v08_project_agenda", quantity: 1 },
      { id: "simple_economy_operation", quantity: 2 },
      { id: "simple_economy_asset", quantity: 1 },
      { id: "simple_upgrade", quantity: 1 },
      { id: "simple_barrier_ice", quantity: 1 },
      { id: "simple_tag_ice", quantity: 1 },
      { id: "v096_trace_probe_ice", quantity: 1 },
      { id: "v08_credit_surge_operation", quantity: 2 },
      { id: "v098_hq_rd_swap_operation", quantity: 1 },
    ],
  },
  demo_runner_099: {
    id: "demo_runner_099",
    name: "Runner Demo Deck 0.99 - Hosting Counter Harness",
    side: "runner",
    identity: "v098_runner_identity",
    cards: [
      { id: "simple_economy_event", quantity: 2 },
      { id: "simple_run_event", quantity: 2 },
      { id: "simple_fracter", quantity: 2 },
      { id: "simple_decoder", quantity: 2 },
      { id: "simple_killer", quantity: 1 },
      { id: "v08_burst_credit_event", quantity: 2 },
      { id: "v095_safehouse_resource", quantity: 1 },
      { id: "v097_deep_dive_event", quantity: 1 },
      { id: "v099_host_resource", quantity: 2 },
      { id: "v099_virus_program", quantity: 2 },
      { id: "v099_recurring_chip", quantity: 2 },
    ],
  },
  demo_corp_099: {
    id: "demo_corp_099",
    name: "Corp Demo Deck 0.99 - Purge Bad Publicity Harness",
    side: "corp",
    identity: "v098_corp_identity",
    cards: [
      { id: "simple_agenda", quantity: 1 },
      { id: "simple_priority_agenda", quantity: 1 },
      { id: "v08_project_agenda", quantity: 1 },
      { id: "simple_economy_operation", quantity: 1 },
      { id: "simple_economy_asset", quantity: 1 },
      { id: "simple_upgrade", quantity: 1 },
      { id: "simple_barrier_ice", quantity: 2 },
      { id: "simple_tag_ice", quantity: 1 },
      { id: "v096_trace_probe_ice", quantity: 1 },
      { id: "v08_credit_surge_operation", quantity: 1 },
      { id: "v099_bad_publicity_operation", quantity: 2 },
    ],
  },
};